spring:
  application:
    name: pontual-iot-api-core
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:pontual_iot}
    username: ${DB_USER:pontual}
    password: ${DB_PASSWORD:pontual123}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  
  data:
    jpa:
      repositories:
        enabled: true
  
  security:
    jwt:
      secret: ${JWT_SECRET:pontual-iot-secret-key-change-in-production}
      expiration: ${JWT_EXPIRATION:86400000} # 24 hours
  
  integration:
    mqtt:
      url: tcp://${MQTT_BROKER:localhost:1883}
      client-id: api-core-${random.uuid}
      username: ${MQTT_USERNAME:}
      password: ${MQTT_PASSWORD:}
      topics:
        device-events: devices/+/events
        device-commands: devices/+/commands

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.pontualiot: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

server:
  port: 8080
  servlet:
    context-path: /api

---
spring:
  config:
    activate:
      on-profile: test
  
  datasource:
    url: jdbc:tc:postgresql:14:///testdb
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: docker
  
  datasource:
    url: jdbc:postgresql://postgres:5432/pontual_iot